package com.creditcard.statement.service;
import com.creditcard.statement.dto.*;import com.creditcard.statement.exception.*;import com.creditcard.statement.model.*;import com.creditcard.statement.repository.*;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.math.RoundingMode;import java.time.*;import java.util.*;import java.util.stream.Collectors;
@Service @RequiredArgsConstructor @Transactional
public class StatementServiceImpl implements StatementService {
    private final StatementRepository stmtRepo;private final TransactionRepository txnRepo;
    public StatementDTO generateStatement(String accountId){List<Transaction> txns=txnRepo.findByAccountIdAndStatementIdIsNull(accountId);BigDecimal purchases=BigDecimal.ZERO,payments=BigDecimal.ZERO,fees=BigDecimal.ZERO,interest=BigDecimal.ZERO;for(Transaction t:txns){switch(t.getTransactionType()){case PURCHASE->purchases=purchases.add(t.getAmount());case PAYMENT,REFUND->payments=payments.add(t.getAmount());case FEE->fees=fees.add(t.getAmount());case INTEREST->interest=interest.add(t.getAmount());}}BigDecimal prevBal=stmtRepo.findTopByAccountIdOrderByStatementDateDesc(accountId).map(Statement::getNewBalance).orElse(BigDecimal.ZERO);BigDecimal newBal=prevBal.subtract(payments).add(purchases).add(fees).add(interest);BigDecimal minPay=newBal.multiply(new BigDecimal("0.02")).max(new BigDecimal("25")).min(newBal.max(BigDecimal.ZERO)).setScale(2,RoundingMode.HALF_UP);Statement stmt=Statement.builder().accountId(accountId).statementNumber("STMT-"+System.currentTimeMillis()).statementDate(LocalDate.now()).dueDate(LocalDate.now().plusDays(25)).previousBalance(prevBal).paymentsReceived(payments).purchases(purchases).fees(fees).interestCharged(interest).newBalance(newBal).minimumPayment(minPay).status(StatementStatus.GENERATED).build();Statement saved=stmtRepo.save(stmt);for(Transaction t:txns){t.setStatementId(saved.getId());txnRepo.save(t);}return mapStmt(saved,txns);}
    @Transactional(readOnly=true) public StatementDTO getStatementById(String id){Statement s=stmtRepo.findById(id).orElseThrow(()->new StatementNotFoundException("Not found"));return mapStmt(s,txnRepo.findByStatementId(id));}
    @Transactional(readOnly=true) public List<StatementDTO> getStatementsByAccountId(String aid){return stmtRepo.findByAccountIdOrderByStatementDateDesc(aid).stream().map(s->mapStmt(s,txnRepo.findByStatementId(s.getId()))).collect(Collectors.toList());}
    public TransactionDTO createTransaction(CreateTransactionRequest req){Transaction t=Transaction.builder().accountId(req.getAccountId()).cardId(req.getCardId()).transactionDate(LocalDateTime.now()).description(req.getDescription()).merchantName(req.getMerchantName()).amount(req.getAmount()).transactionType(req.getTransactionType()).referenceNumber(UUID.randomUUID().toString().substring(0,8).toUpperCase()).build();return mapTxn(txnRepo.save(t));}
    @Transactional(readOnly=true) public List<TransactionDTO> getTransactionsByAccountId(String aid){return txnRepo.findByAccountIdOrderByTransactionDateDesc(aid).stream().map(this::mapTxn).collect(Collectors.toList());}
    @Transactional(readOnly=true) public List<TransactionDTO> getUnbilledTransactions(String aid){return txnRepo.findByAccountIdAndStatementIdIsNull(aid).stream().map(this::mapTxn).collect(Collectors.toList());}
    private StatementDTO mapStmt(Statement s,List<Transaction> txns){return StatementDTO.builder().id(s.getId()).accountId(s.getAccountId()).statementNumber(s.getStatementNumber()).statementDate(s.getStatementDate()).dueDate(s.getDueDate()).previousBalance(s.getPreviousBalance()).paymentsReceived(s.getPaymentsReceived()).purchases(s.getPurchases()).fees(s.getFees()).interestCharged(s.getInterestCharged()).newBalance(s.getNewBalance()).minimumPayment(s.getMinimumPayment()).status(s.getStatus()).transactions(txns.stream().map(this::mapTxn).collect(Collectors.toList())).build();}
    private TransactionDTO mapTxn(Transaction t){return TransactionDTO.builder().id(t.getId()).accountId(t.getAccountId()).cardId(t.getCardId()).statementId(t.getStatementId()).transactionDate(t.getTransactionDate()).description(t.getDescription()).merchantName(t.getMerchantName()).amount(t.getAmount()).transactionType(t.getTransactionType()).status(t.getStatus()).referenceNumber(t.getReferenceNumber()).build();}
}
